version: '3'

services:
    api:
        image: arquivei/go-pipeline:latest
        environment:
            LOG_LEVEL: "DEBUG"
            LOG_HUMAN: "true"
            NFE_STORE: "IN_JSON"
            # NFE_STORE: "IN_MEMORY"
        ports:
          - 8000:8000
        volumes:
            - './:/go/src/github.com/golang-http-server/golang-http-server'
        working_dir: /go/src/github.com/golang-http-server/golang-http-server
        entrypoint:
            - go
            - run
            - -mod=vendor
            - ./