// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	nfe "github.com/golang-http-server/entities/nfe"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// FindByID provides a mock function with given fields: id
func (_m *Repository) FindByID(id string) (nfe.NFeDocument, error) {
	ret := _m.Called(id)

	var r0 nfe.NFeDocument
	if rf, ok := ret.Get(0).(func(string) nfe.NFeDocument); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(nfe.NFeDocument)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: nfeDocument
func (_m *Repository) Save(nfeDocument nfe.NFeDocument) error {
	ret := _m.Called(nfeDocument)

	var r0 error
	if rf, ok := ret.Get(0).(func(nfe.NFeDocument) error); ok {
		r0 = rf(nfeDocument)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
